### ISSUE TITLE
Add a Cloud Run deployment workflow GitHub actions

### ISSUE THREAD

**Issue by satazor** [moxystudio/next-with-moxy#53]
#51 added CI & CD (with Zeit's Now).

However, we are not actually deployment with Docker. So ideally, we would have one workflow with a deployment on Cloud Run.

**Comment by jjperezaguinaga** [comment]
@satazor We actually are deploying w/Cloud Run. Our setup is with GitLab, but I'm sure it's easy enough to port with a similar alternative (e.g. CircleCI). Thought it might help you, so here it is:

```
services:
  - docker:dind

stages:
  - package
  - deploy

variables:
  GCP_PROJECT: gcp-project
  GCP_SERVICE: cloud-run-service
  GCP_REGISTRY: gcr.io/$GCP_PROJECT
  GCP_CLOUD_RUN_PROJECT: $GCP_SERVICE
  PACKAGE_CONTAINER_BUILD_IMAGE: $GCP_REGISTRY/$GCP_SERVICE:build-$CI_COMMIT_REF_SLUG
  URL_PROJECT: https://url

# Multiline Scripts
.deploy-cloud-run: &deploy-cloud-run |
  gcloud run deploy $GCP_CLOUD_RUN_PROJECT --image $PACKAGE_CONTAINER_BUILD_IMAGE \
  --set-env-vars=SECRET=$SECRET,\
  ANOTHER_SECRET=$ANOTHER_SECRET,\
  --platform managed --allow-unauthenticated --region europe-west1

# Scripts to be executed before all tasks
before_script:
  - mkdir -p $HOME/.docker
  - echo "$GITLAB_SERVICE_ACCOUNT_KEY_JSON" >> "$HOME/.docker/config.json"
  - echo "$CLOUD_RUN_SERVICE_ACCOUNT_KEY_JSON" >> "$HOME/google-cloud-run.json"

package:
  stage: package
  image: docker:latest
  script:
    - docker login -u _json_key --password-stdin https://gcr.io < $HOME/.docker/config.json
    - docker build --pull . -t $PACKAGE_CONTAINER_BUILD_IMAGE --cache-from $PACKAGE_CONTAINER_BUILD_IMAGE
    - docker push $PACKAGE_CONTAINER_BUILD_IMAGE

deploy:
  environment:
    name: $GCP_SERVICE
    url: $URL_PROJECT
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file=$HOME/google-cloud-run.json
    - gcloud config set project $GCP_PROJECT
    - *deploy-cloud-run
```
